export const LOGIN_USER = 'LOGIN_USER'; 
export const SINGUP_USER = 'SINGUP_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FETCH_USER = 'FETCH_USER';

export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const MODIFY_CATEGORY = 'MODIFY_CATEGORY';
export const FETCH_CATEGORY = 'FETCH_CATEGORY';

export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const MODIFY_PRODUCT = 'MODIFY_PRODUCT';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';